Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.8/site.py", line 597, in <module>
    main()
  File "/usr/lib/python3.8/site.py", line 584, in main
    known_paths = addsitepackages(known_paths)
  File "/usr/lib/python3.8/site.py", line 367, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/python3.8/site.py", line 214, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.8/site.py", line 175, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/importlib/util.py", line 14, in <module>
    from contextlib import contextmanager
  File "/usr/lib/python3.8/contextlib.py", line 5, in <module>
    from collections import deque
  File "/usr/lib/python3.8/collections/__init__.py", line 61, in <module>
    class _OrderedDictKeysView(_collections_abc.KeysView):
  File "/usr/lib/python3.8/abc.py", line 86, in __new__
    _abc_init(cls)
KeyboardInterrupt
